apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: my-batchjob
spec:
  labels:
    batchjob: batchapp
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t3.xlarge"]
  limits:
    resources:
      cpu: 100
      memory: 100Gi
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-batchjob
spec:
  subnetSelector:
    Name: "{SUBNET_NAME_A},{SUBNET_NAME_B}"
  securityGroupSelector:
    Name: "{YOUR_EKS_SECURIY_GROUP}"
  tags:
    ProvisionerName: "BatchJob"
    NodeType: "AutoProvision"